services:
  # Keycloak Authentication Service
  identity:
    depends_on:
      - postgres
    image: quay.io/keycloak/keycloak:26.2.4
    command: "start --import-realm --http-enabled=true"
    environment:
      KC_HOSTNAME: https://identity-bookingsmart.huypd.dev
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_HEALTH_ENABLED: true
      KC_HTTP_PORT: 80
      # Turnstile Site Key - available to the theme during runtime
      TURNSTILE_SITE_KEY: ${TURNSTILE_SITE_KEY}
    volumes:
      - ./identity/bookingsmart-keycloak-theme.jar:/opt/keycloak/providers/bookingsmart-keycloak-theme.jar
      - ./identity/realm-export.json:/opt/keycloak/data/import/realm-export.json

    networks:
      - booking-network
  # PostgreSQL Database
  postgres:
    image: pgvector/pgvector:pg18
    user: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - booking-network
    command: postgres -c wal_level=logical -c max_replication_slots=5 -c max_wal_senders=5

  # Redis for Event Deduplication
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    networks:
      - booking-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    networks:
      - booking-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    networks:
      - booking-network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka_data:/var/lib/kafka/data



  # Debezium Connect
  connect:
    image: quay.io/debezium/connect:3.2.0.Final
    ports:
      - "8083:8083"
    networks:
      - booking-network
    depends_on:
      - kafka
      - postgres
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: connect

  kafka-setup:
    image: alpine:3.20
    container_name: kafka-setup
    depends_on:
      - kafka
      - connect
    volumes:
      - ./debezium:/tmp/connectors:ro
      - ./wait-for-it.sh:/wait-for-it.sh:ro
    command: >
      sh -lc '
        set -e
        apk add --no-cache curl bash netcat-openbsd

        cp /wait-for-it.sh /tmp/wait-for-it.sh
        sed -i "s/\r$//" /tmp/wait-for-it.sh
        chmod +x /tmp/wait-for-it.sh

        echo "Waiting for Kafka broker..."
        /usr/bin/env bash /tmp/wait-for-it.sh kafka:29092 --timeout=90

        echo "Waiting for Kafka Connect..."
        /usr/bin/env bash /tmp/wait-for-it.sh connect:8083 --timeout=120
        sleep 5
        echo "Deploy flight connector"
        curl -i -X PUT -H "Accept: application/json" -H "Content-Type: application/json" \
          --data-binary @/tmp/connectors/flight-db-connector.json \
          http://connect:8083/connectors/flight-connector/config

        echo "Deploy booking connector"
        curl -i -X PUT -H "Accept: application/json" -H "Content-Type: application/json" \
          --data-binary @/tmp/connectors/booking-saga-outbox-connector.json \
          http://connect:8083/connectors/booking-connector/config

        echo "Deploy hotel connector"
        curl -i -X PUT -H "Accept: application/json" -H "Content-Type: application/json" \
          --data-binary @/tmp/connectors/hotel-db-connector.json \
          http://connect:8083/connectors/hotel-connector/config

        echo "Deploy payment connector"
        curl -i -X PUT -H "Accept: application/json" -H "Content-Type: application/json" \
          --data-binary @/tmp/connectors/payment-db-connector.json \
          http://connect:8083/connectors/payment-connector/config
        echo "Deloy notification connector"
        curl -i -X PUT -H "Accept: application/json" -H "Content-Type: application/json" \
          --data-binary @/tmp/connectors/notification-db-connector.json \
          http://connect:8083/connectors/notification-connector/config
        
      '
    networks:
      - booking-network


  # debezium-ui:
  #   image: quay.io/debezium/debezium-ui:2.1.2.Final
  #   ports:
  #     - "8077:8080"
  #   environment:
  #     KAFKA_CONNECT_URIS: http://connect:8083
  #   networks:
  #     - booking-network
  # # Elasticsearch
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.19.5
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - xpack.security.http.ssl.enabled=false
  #     - xpack.security.transport.ssl.enabled=false
  #     - ES_JAVA_OPTS=-Xms1g -Xmx1g
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   networks:
  #     - booking-network
  #   volumes:
  #     - elasticsearch_data:/usr/share/elasticsearch/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s >/dev/null || exit 1"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 10

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.19.5
  #   container_name: kibana
  #   depends_on:
  #     elasticsearch:
  #       condition: service_healthy
  #   environment:
  #     - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
  #     - XPACK_SECURITY_ENABLED=false
  #   ports:
  #     - "5601:5601"
  #   networks:
  #     - booking-network
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -sf http://localhost:5601/api/status >/dev/null || exit 1"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 10

  # Kafka UI
  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest

  #   ports:
  #     - "8091:8080"
  #   depends_on:
  #     - kafka
  #   networks:
  #     - booking-network
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
  #     KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  # Discovery Service (Eureka)
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    image: phamduyhuyuit/bookingsmart-discovery-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URI=http://discovery-service/eureka
      - SERVER_PORT
    networks:
      - booking-network

  # API Gateway (Backoffice BFF)
  backoffice:
    build:
      context: ./backoffice-bff
      dockerfile: Dockerfile
    image: phamduyhuyuit/bookingsmart-backoffice:latest
    depends_on:
      - postgres # Chỉ đợi postgres healthy
      - identity
    entrypoint:
      [
        "/wait-for-it.sh",
        "identity:80",
        "--timeout=140",
        "--",
        "java",
        "-jar",
        "/app.jar",
      ]
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URI
      - JWT_ISSUER_URI
      - KEYCLOAK_HOST
      - KEYCLOAK_CLIENT_SECRET_BACKOFFICE_BFF
      - SERVER_PORT
      - API_URL
    networks:
      - booking-network

  storefront:
    build:
      context: ./storefront-bff
      dockerfile: Dockerfile
    image: phamduyhuyuit/bookingsmart-storefront:latest
    depends_on:
      - postgres
      - identity
    entrypoint:
      [
        "/wait-for-it.sh",
        "identity:80",
        "--timeout=140",
        "--",
        "java",
        "-jar",
        "/app.jar",
      ]

    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URI
      - JWT_ISSUER_URI
      - KEYCLOAK_HOST
      - KEYCLOAK_CLIENT_SECRET_STOREFRONT_BFF
      - SERVER_PORT
      - API_URL

    networks:
      - booking-network
  storefront-fe:
    build:
      context: ./storefront-fe
      dockerfile: Dockerfile
    image: phamduyhuyuit/bookingsmart-storefront-fe:latest
    environment:
      - NODE_ENV=production

    networks:
      - booking-network
    restart: unless-stopped

  # Backoffice Frontend
  backoffice-fe:
    build:
      context: ./backoffice-fe
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BFF_BASE_URL=${API_URL}
    image: phamduyhuyuit/bookingsmart-backoffice-fe:latest
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://backoffice
      - NEXT_PUBLIC_KEYCLOAK_URL=https://identity/realms/BookingSmart
    networks:
      - booking-network
    restart: unless-stopped
  # Flight Service
  flight-service:
    build:
      context: ./flight-service
      dockerfile: Dockerfile
    image: phamduyhuyuit/bookingsmart-flight-service:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URI
      - DB_URL=jdbc:postgresql://postgres:5432/flight_db
      - DB_USERNAME
      - DB_PASSWORD
      - JWT_ISSUER_URI
      - KAFKA_BOOTSTRAP_SERVERS
      - SERVER_PORT
    networks:
      - booking-network

    # AI Agent Service
  aiAgent-service:
    build:
      context: ./aiAgent-service
      dockerfile: Dockerfile
    image: phamduyhuyuit/bookingsmart-ai-agent-service:latest
    entrypoint:
      [
        "/wait-for-it.sh",
        "identity:80",
        "--timeout=140",
        "--",
        "java",
        "-jar",
        "/app.jar",
      ]
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URI
      - JWT_ISSUER_URI
      - KEYCLOAK_HOST
      - KAFKA_BOOTSTRAP_SERVERS
      - BOOKING_SMART_AI_CLIENT_SECRET
      - SERVER_PORT
      - DB_URL=jdbc:postgresql://postgres:5432/ai_db
      - DB_USERNAME
      - DB_PASSWORD
      - OWM_API_KEY
      - MAPBOX_ACCESS_TOKEN
      - BRAVE_API_KEY
      - MISTRAL_API_KEY
      - GEMINI_API_KEY
      - ELASTIC_URIS
      - ELASTIC_USERNAME
      - ELASTIC_PASSWORD
      - app.flight-service.url=http://flight-service
      - app.hotel-service.url=http://hotel-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Docker socket for running MCP server on containers
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - booking-network
  # Hotel Service
  hotel-service:
    build:
      context: ./hotel-service
      dockerfile: Dockerfile
    image: phamduyhuyuit/bookingsmart-hotel-service:latest
    depends_on:
      postgres:
        condition: service_healthy

    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URI
      - DB_URL=jdbc:postgresql://postgres:5432/hotel_db
      - DB_USERNAME
      - DB_PASSWORD
      - JWT_ISSUER_URI
      - KAFKA_BOOTSTRAP_SERVERS
      - SERVER_PORT
    networks:
      - booking-network

  # Booking Service
  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    image: phamduyhuyuit/bookingsmart-booking-service:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URI
      - DB_URL=jdbc:postgresql://postgres:5432/booking_db
      - DB_USERNAME
      - DB_PASSWORD
      - JWT_ISSUER_URI
      - KAFKA_BOOTSTRAP_SERVERS
      - SERVER_PORT
    networks:
      - booking-network

  # Payment Service
  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    image: phamduyhuyuit/bookingsmart-payment-service:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URI
      - DB_URL=jdbc:postgresql://postgres:5432/payment_db
      - DB_USERNAME
      - DB_PASSWORD
      - JWT_ISSUER_URI
      - KAFKA_BOOTSTRAP_SERVERS
      - SERVER_PORT
      - STRIPE_SECRET_KEY
      - STRIPE_PUBLISHABLE_KEY
    networks:
      - booking-network

  # Notification Service
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    image: phamduyhuyuit/bookingsmart-notification-service:latest
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URI
      - DB_URL=jdbc:postgresql://postgres:5432/notification_db
      - DB_USERNAME
      - DB_PASSWORD
      - JWT_ISSUER_URI
      - KAFKA_BOOTSTRAP_SERVERS
      - SERVER_PORT
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME
      - MAIL_PASSWORD
    networks:
      - booking-network

  # Customer Service
  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    image: phamduyhuyuit/bookingsmart-customer-service:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URI
      - JWT_ISSUER_URI
      - KEYCLOAK_HOST
      - KEYCLOAK_CLIENT_SECRET_CUSTOMER_MANAGEMENT
      - DB_URL=jdbc:postgresql://postgres:5432/customer_db
      - DB_USERNAME
      - DB_PASSWORD
      - SERVER_PORT
      - TURNSTILE_SECRET_KEY
    networks:
      - booking-network
  # Media Service -
  media-service:
    image: phamduyhuyuit/bookingsmart-media-service:latest
    build:
      context: ./media-service
      dockerfile: Dockerfile
    depends_on:
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URI
      - JWT_ISSUER_URI
      - KAFKA_BOOTSTRAP_SERVERS
      - SERVER_PORT
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET
      - DB_URL=jdbc:postgresql://postgres:5432/media_db
      - DB_USERNAME
      - DB_PASSWORD
    networks:
      - booking-network

  # Nginx Reverse Proxy - API Gateway for Cloudflare Tunnel
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - booking-network
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - booking-network

  #Ollama
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    ports:
      - "11434:11434"
    volumes:
      - pulled_models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - booking-network
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redis-insight-data:/data
    networks:
      - booking-network
    depends_on:
      - redis

networks:
  booking-network:
    driver: bridge
    name: booking-network
volumes:
  postgres_data:
  redis_data:
  redis-insight-data:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
  # elasticsearch_data:
  pulled_models: